LABEL_ALL_TOKENS: True
SLIDING_WIN_SIZE: 4
HAVE_PRE: False
MODEL_PATH: Jean-Baptiste/camembert-ner-with-dates
DATA_FILE_PATH: eval_data/eval_data.json
PRE_LABEL: B-DATE
CEN_LABEL: I-DATE
DEFAULT_LABEL: I-DATE
ADD_SPECIAL_TOKENS: True
USE_SPECIAL_TOKENS: False
WORD_TRUE_TOR: 0.4
WORD_FALSE_TOR: 1

